export const PERMISSIONS = {
    // Dashboard
    DASHBOARD: 'DASHBOARD',

    // Pacientes
    PATIENTS_VIEW: 'PATIENTS_VIEW',
    PATIENTS_CREATE: 'PATIENTS_CREATE',
    PATIENTS_EDIT: 'PATIENTS_EDIT',
    PATIENTS_DELETE: 'PATIENTS_DELETE',

    // Doctores
    DOCTORS_VIEW: 'DOCTORS_VIEW',
    DOCTORS_CREATE: 'DOCTORS_CREATE',
    DOCTORS_EDIT: 'DOCTORS_EDIT',
    DOCTORS_DELETE: 'DOCTORS_DELETE',

    // Citas
    APPOINTMENTS_VIEW: 'APPOINTMENTS_VIEW',
    APPOINTMENTS_CREATE: 'APPOINTMENTS_CREATE',
    APPOINTMENTS_EDIT: 'APPOINTMENTS_EDIT',
    APPOINTMENTS_DELETE: 'APPOINTMENTS_DELETE',

    // Emergencias
    EMERGENCY_VIEW: 'EMERGENCY_VIEW',
    EMERGENCY_CREATE: 'EMERGENCY_CREATE',
    EMERGENCY_EDIT: 'EMERGENCY_EDIT',
    EMERGENCY_DELETE: 'EMERGENCY_DELETE',
    EMERGENCY_DISCHARGE: 'EMERGENCY_DISCHARGE',

    // Gestión de Camas
    BEDS_VIEW: 'BEDS_VIEW',
    BEDS_ASSIGN: 'BEDS_ASSIGN',
    BEDS_EDIT: 'BEDS_EDIT',
    BEDS_DELETE: 'BEDS_DELETE',

    // Farmacia
    PHARMACY_VIEW: 'PHARMACY_VIEW',
    PHARMACY_CREATE: 'PHARMACY_CREATE',
    PHARMACY_EDIT: 'PHARMACY_EDIT',
    PHARMACY_DELETE: 'PHARMACY_DELETE',
    PHARMACY_DISPENSE: 'PHARMACY_DISPENSE',

    // Laboratorio
    LAB_VIEW: 'LAB_VIEW',
    LAB_CREATE: 'LAB_CREATE',
    LAB_EDIT: 'LAB_EDIT',
    LAB_DELETE: 'LAB_DELETE',
    LAB_RESULTS: 'LAB_RESULTS',

    // Facturación
    BILLING_VIEW: 'BILLING_VIEW',
    BILLING_CREATE: 'BILLING_CREATE',
    BILLING_EDIT: 'BILLING_EDIT',
    BILLING_DELETE: 'BILLING_DELETE',

    // Reportes
    REPORTS_VIEW: 'REPORTS_VIEW',
    REPORTS_CREATE: 'REPORTS_CREATE',
    REPORTS_EXPORT: 'REPORTS_EXPORT',

    // Analítica
    ANALYTICS_VIEW: 'ANALYTICS_VIEW',
    ANALYTICS_ADVANCED: 'ANALYTICS_ADVANCED',

    // IA
    AI_USE: 'AI_USE',
    AI_CONFIG: 'AI_CONFIG',

    // Mensajes
    MESSAGES_VIEW: 'MESSAGES_VIEW',
    MESSAGES_SEND: 'MESSAGES_SEND',

    // RRHH
    HR_VIEW: 'HR_VIEW',
    HR_CREATE: 'HR_CREATE',
    HR_EDIT: 'HR_EDIT',
    HR_DELETE: 'HR_DELETE',

    // Asistencia
    ATTENDANCE_VIEW: 'ATTENDANCE_VIEW',
    ATTENDANCE_EDIT: 'ATTENDANCE_EDIT',
    ATTENDANCE_DELETE: 'ATTENDANCE_DELETE',

    // Administración (Usuarios)
    ADMIN_VIEW: 'ADMIN_VIEW',
    ADMIN_CREATE: 'ADMIN_CREATE',
    ADMIN_EDIT: 'ADMIN_EDIT',
    ADMIN_DELETE: 'ADMIN_DELETE',
    AUDIT_VIEW: 'AUDIT_VIEW',

    // Configuración
    SETTINGS_VIEW: 'SETTINGS_VIEW',
    SETTINGS_EDIT: 'SETTINGS_EDIT',

    // Sala de Espera
    WAITING_VIEW: 'WAITING_VIEW',
    WAITING_MANAGE: 'WAITING_MANAGE',

    // Expedientes Médicos
    MEDICAL_RECORDS_VIEW: 'MEDICAL_RECORDS_VIEW',
    MEDICAL_RECORDS_CREATE: 'MEDICAL_RECORDS_CREATE',
    MEDICAL_RECORDS_EDIT: 'MEDICAL_RECORDS_EDIT',
    MEDICAL_RECORDS_DELETE: 'MEDICAL_RECORDS_DELETE',

    // Recetas Médicas
    PRESCRIPTIONS_VIEW: 'PRESCRIPTIONS_VIEW',
    PRESCRIPTIONS_CREATE: 'PRESCRIPTIONS_CREATE',
    PRESCRIPTIONS_EDIT: 'PRESCRIPTIONS_EDIT',
    PRESCRIPTIONS_DELETE: 'PRESCRIPTIONS_DELETE',

    // Respaldos y Seguridad
    BACKUPS_VIEW: 'BACKUPS_VIEW',
    BACKUPS_CREATE: 'BACKUPS_CREATE',
    BACKUPS_RESTORE: 'BACKUPS_RESTORE',
    BACKUPS_DELETE: 'BACKUPS_DELETE',

    // Especiales
    ALL: 'ALL',
} as const

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS]
